### ISSUE TITLE
error when running example vignette

### ISSUE THREAD

**Issue by helenmasson** [herdiantrisufriyana/clixo#1]
I am trying to familiarize myself with the package by simply running the example vignette:
# Load packages
library(clixo)
library(tidyverse)

# Load simulated data
input=input_example()

# Create CliXO
ontology=clixo(input$similarity)

However the clixo function (last line) results in the following error:
fatal: destination path 'clixo_0.3' already exists and is not an empty directory.
bash: clixo_0.3/clixo: cannot execute binary file
Error: Problem with `mutate()` input `relation`.
object 'relation' not found
Input `relation` is `ifelse(relation == "default", "is_a", feature_name)`.

**Comment by herdiantrisufriyana** [comment]
Thanks for telling me this. I updated this package into 0.1.1 to fix this issue.

You need to remove that version then follow the vignette. Do not forget to delete previous clixo_0.3 if you run this program in the same folder as the working directory. For the new version, it automatically removes that folder if there's an error. I just simply clone the original C++ program during the function is working then remove it when it's done.

This issue happens because I compiled the the original clixo C++ program in linux. You can read explanation for this kind of problem [here](https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error). The clixo 0.1.1 version use specific compilation of the clixo C++ program depending on your operating system. I assumed you used windows because I reproduce your error on my windows machine. Tell me if it works or not.

**Comment by herdiantrisufriyana** [comment]
And do not forget to delete previous clixo_0.3 if you run this program in the same folder as the working directory. For the new version, it automatically removes that folder if there's an error. I just simply clone the original C++ program during the function is working then remove it when it's done.
