### ISSUE TITLE
unused argument (os='mac')

### ISSUE THREAD

**Issue by helenmasson** [herdiantrisufriyana/clixo#2]
I am trying to run the example vignette in Rstudio on my mac, and I encounter an error when I try to run the clixo function:
> input <- input_example()
> ontology <- clixo(input$similarity, os='mac')
Error in clixo(input$similarity, os = "mac") : 
  unused argument (os = "mac")

**Comment by herdiantrisufriyana** [comment]
Based on the error message, it seems the 'clixo' function has not been updated, like the previous one when 'os' argument wasn't there yet. Have you remove previous installation of clixo, and re-install it?

When you re-install, it should automatically use the newer version of 'clixo' package. 

Try to remove it first, then re-install it:

`remove.packages('clixo')`
`devtools::install_github('herdiantrisufriyana/clixo')`

If you're in a session after loading the package, restart your IDE (e.g. RStudio) first or restart session before appying the codes above.

**Comment by helenmasson** [comment]
I've removed and reinstalled clixo according to your instructions above.
That solved the original issue of recognizing the 'os' argument, but now I have a new yet familiar error haha (my previous issue).  Sorry to be bothering you so much.
Here is the new error when I run the code:
> input <- input_example()
> ontology <- clixo(input$similarity, os="mac")
fatal: destination path 'clixo_0.3' already exists and is not an empty directory.
bash: clixo_0.3/clixo: cannot execute binary file
Error: Problem with `mutate()` input `relation`.
object 'relation' not found
Input `relation` is `ifelse(relation == "default", "is_a", feature_name)`.

When I run rland::last_error() to see where the error occured:
<error/dplyr:::mutate_error>
Problem with `mutate()` input `relation`.
x object 'relation' not found
Input `relation` is `ifelse(relation == "default", "is_a", feature_name)`.
Backtrace:
  1. clixo::clixo(input$similarity, os = "mac")
 10. base::.handleSimpleError(...)
 11. dplyr:::h(simpleError(msg, call))

**Comment by herdiantrisufriyana** [comment]
Never mind :)
I'm committed to maintain this package. 

I guess that's because you do not remove the clixo_0.3 folder from the last error (when using the old version of this clixo package). When you ran this new version (in the same folder, while there's already the clixo_0.3 folder), this package is unable to overwrite that folder. I know this from this line of the message error:

> fatal: destination path 'clixo_0.3' already exists and is not an empty directory.

This function just continue the next codes although there is such kind of error, so just ignore the next messages for this time.

**Comment by helenmasson** [comment]
Can I ask you an unrelated question?  (I'm new to bioinformatics/comp biology/git so I'm not sure if it's ok to be asking these questions via github, so please let me know if this is not appropriate and what other ways I would be able to ask these kinds of questions):
How would you recommend processing similarity data for the best results using clixo?  For example if I want to used an interaction or PPI network (ex STRING), how would you recommend processing the data?  I currently have a subset of STRING it in the form of an adjacency matrix.  It is unsurprisingly super sparse with a min of 0 and a max of 999.  Would you recomment preforming some sort of transformation before running Clixo?  Does the similarity matrix need to be between -1 and 1 (like most correlation measures)?
Any advice would be greatly appreciated!  Thank you!

**Comment by herdiantrisufriyana** [comment]
Yes, I will answer that question here. In addition, you may also find more useful answers in Biostar, and Stackoverflow (mostly).

Following the inventor (https://academic.oup.com/bioinformatics/article/30/12/i34/389066), I used Pearson correlation matrix. As described in section 2.3.1. in that paper, this algorithm works using similarity instead of distance. It means if a similarity metric for a pair of entities is farther to zero (either positive or negative), the algorithm prefer to include this pair into a group.  In similarity metric, farther to zero means similar. But, in distance metric, that means dissimilar. Beware that CliXO cannot differentiate similarity or distance metric. Thus, you need to find out what metric that STRING matrix used (I don't know). If it used distance metric, then you need to substract it such that the number being reverse (from dissimilarity to similarity).

They also used Resnik semantic similarity for GO BP term-to-term similarity because of comparing each pair of gene sets, instead of comparing a pair of scalar numbers.

An R package, parallelDist, have a function to create similarity/distance matrices (they only call it as distance matrix). There are a tremendous metrics you can use. Try to pay attention to the equation for each metric. That will show you what would be the biological relevance for each metric. But, frankly, mostly Pearson will work, but computationally expensive (difficult to compute for larger matrix). As alternative, cosine similarity is computationally cheaper.

Before creating a similarity/distance matrix, it is usually better if you centered the  number by subtracting each with the column-wise mean, where the columns are features while the rows are instances. Then you can create a feature-to-feature matrix (depending on the function, but mostly it will compute column to column, just check the output). But, I personally also standardize the value by dividing the centered number by the column-wise standard deviation. Thus, the number interval is equivalent among the pair, easier to understand.

If you already got the matrix, then you may also transform it. Just make sure that value farther to zero should mean more similar. This is needed particularly for CliXO.
